name: flutter_serial_port
description: Serial Port for Flutter (FFI bindings to libserialport,
  a minimal C-library by sigrok).
version: 0.0.1
homepage: https://github.com/jpnurmi/flutter_serial_port
repository: https://github.com/jpnurmi/flutter_serial_port
issue_tracker: https://github.com/jpnurmi/flutter_serial_port/issues

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_serial_port: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterSerialPortPlugin
        package: org.sigrok.flutter_serial_port
      linux:
        pluginClass: FlutterSerialPortPlugin
      windows:
        pluginClass: FlutterSerialPortPlugin
