name: flutter_serialport
description: A simple wrapper around libserialport utilizing Flutter's
  build system to build and deploy the C-library for the target platform.
version: 0.1.0
homepage: https://github.com/jpnurmi/flutter_serialport
repository: https://github.com/jpnurmi/flutter_serialport
issue_tracker: https://github.com/jpnurmi/flutter_serialport/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  libserialport: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterSerialPortPlugin
        package: org.sigrok.flutter_serial_port
      linux:
        pluginClass: FlutterSerialPortPlugin
      macos:
        pluginClass: FlutterSerialPortPlugin
      windows:
        pluginClass: FlutterSerialPortPlugin
